# Generated by Django 5.1 on 2024-09-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_modifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='location',
        ),
    ]
