# Generated by Django 5.1 on 2024-09-04 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_address_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier', to='restaurants.fooditem'),
        ),
    ]
